
DELETE FROM USER_TBL WHERE username='Lee123';
DELETE FROM USERPRFL_TBL WHERE username='Lee123';

commit;

SELECT count(*) FROM USER_TBL;
SELECT count(*) FROM USERPRFL_TBL;


SELECT  * FROM USER_TBL;
SELECT  * FROM USERPRFL_TBL;
