
# Common
RootFolder: "./res"

# DB INFO
DBName: mysql
DBConnStr: root:123456@/THDATABASE

# DEV Debug info
EnableDEVLog: true
LOGFolder: "./ALLLOGS"

# file for HTTP defines
HTTPPkgCfgFile:  "./res/httpcfg.yaml"

# Module defines
RootModule: "workshop"
Modules: [workshop]
IndexResources:  ["IndexPage"]
